[2025-01-30T02:26:01.830+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-30T02:26:01.860+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etapa1_dag.validar manual__2025-01-30T02:25:52.545176+00:00 [queued]>
[2025-01-30T02:26:01.873+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etapa1_dag.validar manual__2025-01-30T02:25:52.545176+00:00 [queued]>
[2025-01-30T02:26:01.874+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-30T02:26:01.899+0000] {taskinstance.py:2889} INFO - Executing <Task(BranchPythonOperator): validar> on 2025-01-30 02:25:52.545176+00:00
[2025-01-30T02:26:01.912+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=101) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-30T02:26:01.914+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etapa1_dag', 'validar', 'manual__2025-01-30T02:25:52.545176+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/etapa1_dag.py', '--cfg-path', '/tmp/tmpup2nj61d']
[2025-01-30T02:26:01.915+0000] {standard_task_runner.py:72} INFO - Started process 104 to run task
[2025-01-30T02:26:01.916+0000] {standard_task_runner.py:105} INFO - Job 5: Subtask validar
[2025-01-30T02:26:02.252+0000] {task_command.py:467} INFO - Running <TaskInstance: etapa1_dag.validar manual__2025-01-30T02:25:52.545176+00:00 [running]> on host 1899222f083d
[2025-01-30T02:26:02.364+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etapa1_dag' AIRFLOW_CTX_TASK_ID='validar' AIRFLOW_CTX_EXECUTION_DATE='2025-01-30T02:25:52.545176+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-30T02:25:52.545176+00:00'
[2025-01-30T02:26:02.365+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-30T02:26:02.366+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-30T02:26:02.366+0000] {logging_mixin.py:190} INFO - Current task name:validar state:running start_date:2025-01-30 02:26:01.861143+00:00
[2025-01-30T02:26:02.367+0000] {logging_mixin.py:190} INFO - Dag name:etapa1_dag and current dag run status:running
[2025-01-30T02:26:02.367+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-30T02:26:02.368+0000] {baseoperator.py:421} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2025-01-30T02:26:02.383+0000] {python.py:240} INFO - Done. Returned value was: copia
[2025-01-30T02:26:02.384+0000] {branch.py:38} INFO - Branch into copia
[2025-01-30T02:26:02.385+0000] {skipmixin.py:230} INFO - Following branch ('copia',)
[2025-01-30T02:26:02.404+0000] {skipmixin.py:278} INFO - Skipping tasks [('invalido', -1)]
[2025-01-30T02:26:02.452+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-30T02:26:02.453+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etapa1_dag, task_id=validar, run_id=manual__2025-01-30T02:25:52.545176+00:00, execution_date=20250130T022552, start_date=20250130T022601, end_date=20250130T022602
[2025-01-30T02:26:02.468+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-01-30T02:26:02.471+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-01-30T02:26:02.472+0000] {logging_mixin.py:190} INFO - Dag name:etapa1_dag queued_at:2025-01-30 02:25:52.589800+00:00
[2025-01-30T02:26:02.472+0000] {logging_mixin.py:190} INFO - Task hostname:1899222f083d operator:BranchPythonOperator
[2025-01-30T02:26:02.533+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-30T02:26:02.791+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-01-30T02:26:02.796+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
