[2025-01-28T02:24:53.823+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-28T02:24:53.861+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etapa1_dag.valido manual__2025-01-28T02:21:52.102766+00:00 [queued]>
[2025-01-28T02:24:53.888+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etapa1_dag.valido manual__2025-01-28T02:21:52.102766+00:00 [queued]>
[2025-01-28T02:24:53.890+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-28T02:24:53.931+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): valido> on 2025-01-28 02:21:52.102766+00:00
[2025-01-28T02:24:53.948+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=311) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-28T02:24:53.951+0000] {standard_task_runner.py:72} INFO - Started process 319 to run task
[2025-01-28T02:24:53.953+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etapa1_dag', 'valido', 'manual__2025-01-28T02:21:52.102766+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/etapa1_dag.py', '--cfg-path', '/tmp/tmpsz9so4sv']
[2025-01-28T02:24:53.955+0000] {standard_task_runner.py:105} INFO - Job 14: Subtask valido
[2025-01-28T02:24:54.058+0000] {task_command.py:467} INFO - Running <TaskInstance: etapa1_dag.valido manual__2025-01-28T02:21:52.102766+00:00 [running]> on host 90d9eb5798dc
[2025-01-28T02:24:54.294+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etapa1_dag' AIRFLOW_CTX_TASK_ID='valido' AIRFLOW_CTX_EXECUTION_DATE='2025-01-28T02:21:52.102766+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-28T02:21:52.102766+00:00'
[2025-01-28T02:24:54.297+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-28T02:24:54.298+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-28T02:24:54.298+0000] {logging_mixin.py:190} INFO - Current task name:valido state:running start_date:2025-01-28 02:24:53.863230+00:00
[2025-01-28T02:24:54.299+0000] {logging_mixin.py:190} INFO - Dag name:etapa1_dag and current dag run status:running
[2025-01-28T02:24:54.300+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-28T02:24:54.301+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-01-28T02:24:54.304+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', "echo 'OK'"]
[2025-01-28T02:24:54.336+0000] {subprocess.py:99} INFO - Output:
[2025-01-28T02:24:54.347+0000] {subprocess.py:106} INFO - OK
[2025-01-28T02:24:54.348+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-01-28T02:24:54.390+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-28T02:24:54.392+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etapa1_dag, task_id=valido, run_id=manual__2025-01-28T02:21:52.102766+00:00, execution_date=20250128T022152, start_date=20250128T022453, end_date=20250128T022454
[2025-01-28T02:24:54.414+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-01-28T02:24:54.414+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-01-28T02:24:54.416+0000] {logging_mixin.py:190} INFO - Dag name:etapa1_dag queued_at:2025-01-28 02:24:45.090491+00:00
[2025-01-28T02:24:54.417+0000] {logging_mixin.py:190} INFO - Task hostname:90d9eb5798dc operator:BashOperator
[2025-01-28T02:24:54.460+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-28T02:24:54.486+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-28T02:24:54.495+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
