[2025-01-28T02:28:29.899+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-28T02:28:29.922+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etapa1_dag.valido manual__2025-01-28T02:28:21.310287+00:00 [queued]>
[2025-01-28T02:28:29.934+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etapa1_dag.valido manual__2025-01-28T02:28:21.310287+00:00 [queued]>
[2025-01-28T02:28:29.934+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-28T02:28:30.082+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): valido> on 2025-01-28 02:28:21.310287+00:00
[2025-01-28T02:28:30.090+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=397) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-28T02:28:30.092+0000] {standard_task_runner.py:72} INFO - Started process 402 to run task
[2025-01-28T02:28:30.092+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etapa1_dag', 'valido', 'manual__2025-01-28T02:28:21.310287+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/etapa1_dag.py', '--cfg-path', '/tmp/tmpj5bu75lg']
[2025-01-28T02:28:30.093+0000] {standard_task_runner.py:105} INFO - Job 24: Subtask valido
[2025-01-28T02:28:30.145+0000] {task_command.py:467} INFO - Running <TaskInstance: etapa1_dag.valido manual__2025-01-28T02:28:21.310287+00:00 [running]> on host 90d9eb5798dc
[2025-01-28T02:28:30.245+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etapa1_dag' AIRFLOW_CTX_TASK_ID='valido' AIRFLOW_CTX_EXECUTION_DATE='2025-01-28T02:28:21.310287+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-28T02:28:21.310287+00:00'
[2025-01-28T02:28:30.246+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-28T02:28:30.247+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-28T02:28:30.247+0000] {logging_mixin.py:190} INFO - Current task name:valido state:running start_date:2025-01-28 02:28:29.922799+00:00
[2025-01-28T02:28:30.247+0000] {logging_mixin.py:190} INFO - Dag name:etapa1_dag and current dag run status:running
[2025-01-28T02:28:30.248+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-28T02:28:30.249+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-01-28T02:28:30.250+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', "echo 'OK'"]
[2025-01-28T02:28:30.266+0000] {subprocess.py:99} INFO - Output:
[2025-01-28T02:28:30.268+0000] {subprocess.py:106} INFO - OK
[2025-01-28T02:28:30.268+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-01-28T02:28:30.297+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-28T02:28:30.298+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etapa1_dag, task_id=valido, run_id=manual__2025-01-28T02:28:21.310287+00:00, execution_date=20250128T022821, start_date=20250128T022829, end_date=20250128T022830
[2025-01-28T02:28:30.310+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-01-28T02:28:30.311+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-01-28T02:28:30.312+0000] {logging_mixin.py:190} INFO - Dag name:etapa1_dag queued_at:2025-01-28 02:28:21.323066+00:00
[2025-01-28T02:28:30.312+0000] {logging_mixin.py:190} INFO - Task hostname:90d9eb5798dc operator:BashOperator
[2025-01-28T02:28:30.347+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-28T02:28:30.366+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-28T02:28:30.370+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
