[2025-01-28T02:24:55.967+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-28T02:24:55.987+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etapa1_dag.validade manual__2025-01-28T02:24:48.799519+00:00 [queued]>
[2025-01-28T02:24:55.996+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etapa1_dag.validade manual__2025-01-28T02:24:48.799519+00:00 [queued]>
[2025-01-28T02:24:55.998+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-28T02:24:56.183+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): validade> on 2025-01-28 02:24:48.799519+00:00
[2025-01-28T02:24:56.194+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=317) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-28T02:24:56.196+0000] {standard_task_runner.py:72} INFO - Started process 325 to run task
[2025-01-28T02:24:56.196+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etapa1_dag', 'validade', 'manual__2025-01-28T02:24:48.799519+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/etapa1_dag.py', '--cfg-path', '/tmp/tmp28s7ndf4']
[2025-01-28T02:24:56.197+0000] {standard_task_runner.py:105} INFO - Job 16: Subtask validade
[2025-01-28T02:24:56.260+0000] {task_command.py:467} INFO - Running <TaskInstance: etapa1_dag.validade manual__2025-01-28T02:24:48.799519+00:00 [running]> on host 90d9eb5798dc
[2025-01-28T02:24:56.368+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etapa1_dag' AIRFLOW_CTX_TASK_ID='validade' AIRFLOW_CTX_EXECUTION_DATE='2025-01-28T02:24:48.799519+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-28T02:24:48.799519+00:00'
[2025-01-28T02:24:56.369+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-28T02:24:56.370+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-28T02:24:56.370+0000] {logging_mixin.py:190} INFO - Current task name:validade state:running start_date:2025-01-28 02:24:55.987977+00:00
[2025-01-28T02:24:56.371+0000] {logging_mixin.py:190} INFO - Dag name:etapa1_dag and current dag run status:running
[2025-01-28T02:24:56.371+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-28T02:24:56.383+0000] {python.py:240} INFO - Done. Returned value was: valido
[2025-01-28T02:24:56.410+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-28T02:24:56.411+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etapa1_dag, task_id=validade, run_id=manual__2025-01-28T02:24:48.799519+00:00, execution_date=20250128T022448, start_date=20250128T022455, end_date=20250128T022456
[2025-01-28T02:24:56.424+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-01-28T02:24:56.425+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-01-28T02:24:56.425+0000] {logging_mixin.py:190} INFO - Dag name:etapa1_dag queued_at:2025-01-28 02:24:48.813048+00:00
[2025-01-28T02:24:56.426+0000] {logging_mixin.py:190} INFO - Task hostname:90d9eb5798dc operator:PythonOperator
[2025-01-28T02:24:56.452+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-28T02:24:56.477+0000] {taskinstance.py:3895} INFO - 2 downstream tasks scheduled from follow-on schedule check
[2025-01-28T02:24:56.484+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
