[2025-01-30T02:37:05.856+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-30T02:37:05.891+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etapa1_dag.copia manual__2025-01-30T02:27:39.702949+00:00 [queued]>
[2025-01-30T02:37:05.908+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etapa1_dag.copia manual__2025-01-30T02:27:39.702949+00:00 [queued]>
[2025-01-30T02:37:05.909+0000] {taskinstance.py:2866} INFO - Starting attempt 4 of 4
[2025-01-30T02:37:06.079+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): copia> on 2025-01-30 02:27:39.702949+00:00
[2025-01-30T02:37:06.088+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=300) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-30T02:37:06.090+0000] {standard_task_runner.py:72} INFO - Started process 302 to run task
[2025-01-30T02:37:06.091+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etapa1_dag', 'copia', 'manual__2025-01-30T02:27:39.702949+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/etapa1_dag.py', '--cfg-path', '/tmp/tmp_1m4rh_v']
[2025-01-30T02:37:06.092+0000] {standard_task_runner.py:105} INFO - Job 20: Subtask copia
[2025-01-30T02:37:06.144+0000] {task_command.py:467} INFO - Running <TaskInstance: etapa1_dag.copia manual__2025-01-30T02:27:39.702949+00:00 [running]> on host 1899222f083d
[2025-01-30T02:37:06.245+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etapa1_dag' AIRFLOW_CTX_TASK_ID='copia' AIRFLOW_CTX_EXECUTION_DATE='2025-01-30T02:27:39.702949+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-30T02:27:39.702949+00:00'
[2025-01-30T02:37:06.247+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-30T02:37:06.247+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-30T02:37:06.248+0000] {logging_mixin.py:190} INFO - Current task name:copia state:running start_date:2025-01-30 02:37:05.891914+00:00
[2025-01-30T02:37:06.248+0000] {logging_mixin.py:190} INFO - Dag name:etapa1_dag and current dag run status:running
[2025-01-30T02:37:06.249+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-30T02:37:06.334+0000] {logging_mixin.py:190} INFO - Erro durante a execução: This Connection is closed
[2025-01-30T02:37:06.335+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-30T02:37:06.350+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-30T02:37:06.351+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etapa1_dag, task_id=copia, run_id=manual__2025-01-30T02:27:39.702949+00:00, execution_date=20250130T022739, start_date=20250130T023705, end_date=20250130T023706
[2025-01-30T02:37:06.365+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-01-30T02:37:06.365+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-01-30T02:37:06.366+0000] {logging_mixin.py:190} INFO - Dag name:etapa1_dag queued_at:2025-01-30 02:36:57.682085+00:00
[2025-01-30T02:37:06.366+0000] {logging_mixin.py:190} INFO - Task hostname:1899222f083d operator:PythonOperator
[2025-01-30T02:37:06.386+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-30T02:37:06.405+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-30T02:37:06.408+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
